version: "3"

services:
  namenode:
    image: liteonlab/hadoop-namenode:1.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    expose:
      - "9000"
    ports:
      - 50070:50070
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoopbase/hadoop.env

  datanode:
    image: liteonlab/hadoop-datanode:1.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      - ./data:/data
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoopbase/hadoop.env

  resourcemanager:
    image: liteonlab/hadoop-resourcemanager:1.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoopbase/hadoop.env

  nodemanager1:
    image: liteonlab/hadoop-nodemanager:1.0.0-hadoop2.7.4-java8
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    ports:
      - 8042:8042
    env_file:
      - ./hadoopbase/hadoop.env

  historyserver:
    image: liteonlab/hadoop-historyserver:1.0.0-hadoop2.7.4-java8
    container_name: historyserver
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    ports:
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoopbase/hadoop.env

  submit:
    image: liteonlab/hadoop-submit:1.0.0-hadoop2.7.4-java8
    container_name: submit
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoopbase/hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
