FROM jupyter/datascience-notebook
RUN pip install --upgrade pip
RUN pip install pymysql

#USER root

VOLUME /home/jovyan/work
#ADD code/hbase_query_filter.ipynb /home/jovyan/work
#ADD code/hbsae_exercise.ipynb /home/jovyan/work
#ADD code/iot_sample_data.ipynb /home/jovyan/work
#RUN chown -R jovyan:users /home/jovyan/work

#USER jovyan

