version: "3"

services:
  namenode:
    image: orozcohsu/hadoop-namenode:1.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "9000"
    ports:
      - 50070:50070
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoopbase/hadoop.env

  datanode:
    image: orozcohsu/hadoop-datanode:1.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoopbase/hadoop.env

  resourcemanager:
    image: orozcohsu/hadoop-resourcemanager:1.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoopbase/hadoop.env
    volumes:
      - /etc/localtime:/etc/localtime:ro

  nodemanager:
    image: orozcohsu/hadoop-nodemanager:1.0.0-hadoop2.7.4-java8
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoopbase/hadoop.env
    volumes:
      - /etc/localtime:/etc/localtime:ro

  historyserver:
    image: orozcohsu/hadoop-historyserver:1.0.0-hadoop2.7.4-java8
    container_name: historyserver
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    ports:
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoopbase/hadoop.env
    volumes:
      - /etc/localtime:/etc/localtime:ro

  zoo:
    image: zookeeper:3.4.10
    container_name: zoo
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
      - 2181:2181
    volumes:
      - /etc/localtime:/etc/localtime:ro

  submit:
    image: orozcohsu/hadoop-submit:1.0.0-hadoop2.7.4-java8
    container_name: submit
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoopbase/hadoop.env
    volumes:
      - /etc/localtime:/etc/localtime:ro

  driver:
    image: orozcohsu/hadoop-driver:1.0.0-hadoop2.7.4-java8
    container_name: driver
    volumes:
      - ./data:/data  
      - /etc/localtime:/etc/localtime:ro
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    command: tail -f /dev/null
    env_file:
      - ./hadoopbase/hadoop.env

  hbase-master:
    image: orozcohsu/hbase-master:1.0.0-hbase1.4.13
    container_name: hbase-master
    depends_on:
      - "namenode"
      - "resourcemanager"
    hostname: hbase-master
    env_file:
      - ./hivehbase/hbase-distributed-local.env
    environment:
      SERVICE_PRECONDITION: "namenode:9000 datanode:50075 zoo:2181"
    ports:
      - 16010:16010
      - 4444:4444
    volumes:
      - /etc/localtime:/etc/localtime:ro

  hbase-region:
    image: orozcohsu/hbase-regionserver:1.0.0-hbase1.4.13
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    env_file:
      - ./hivehbase/hbase-distributed-local.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "namenode:9000 datanode:50075 zoo:2181 hbase-master:16010"
    ports:
      - 16030:16030
    volumes:
      - /etc/localtime:/etc/localtime:ro

  hive-server:
    image: orozcohsu/hive-server:1.0.0-hive2.3.2
    container_name: hive-server
    env_file:
      - ./hivehbase/hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:mysql://metadata/hive?useSSL=false"
      SERVICE_PRECONDITION: "namenode:9000 datanode:50075 hive-metastore:9083"
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  hive-metastore:
    image: orozcohsu/hive-server:1.0.0-hive2.3.2
    container_name: hive-metastore
    env_file:
      - ./hivehbase/hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    depends_on:
      - "metadata"
    environment:
      SERVICE_PRECONDITION: "namenode:9000 datanode:50075"
    ports:
      - "9083:9083"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  presto-coordinator:
    image: orozcohsu/prestodb:1.0.0-prestodb0.181
    container_name: prestodb
    ports:
      - "8089:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  metadata:
    image: mysql:5.7
    container_name: metadata
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: hive
        MYSQL_USER: hive
        MYSQL_PASSWORD: hive
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
      - metadata:/var/lib/mysql/

  jupyter:
    image: orozcohsu/jupyter:1.0.0
    container_name: jupyter
    ports:
      - 8888:8888
    command: start-notebook.sh --NotebookApp.token='1qaz@WSX'
    healthcheck:
        test: ["CMD", "curl", "-f", "localhost:8888"]
        timeout: 20s
        retries: 10
    volumes:
      - ./jupyter/code:/home/jovyan/work:rw
      - /etc/localtime:/etc/localtime:ro

  nodered:
    image: orozcohsu/nodered:1.0.0-v6
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - nodered:/data
    volumes:
      - /etc/localtime:/etc/localtime:ro

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  metadata:
  nodered:
